# Disable SPI
CONFIG_SPI=n
CONFIG_PWM=n
CONFIG_PWM_NRFX=n
CONFIG_I2C=n

#EXT Power management
CONFIG_ZMK_EXT_POWER=n

# Disable unused display on left hand
CONFIG_ZMK_DISPLAY=n

#Enable Deep Sleep on left hand(without trackpoint) for better battery life
CONFIG_ZMK_SLEEP=y
# Go to sleep after 25 mins (25*60*1000ms)
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1500000
# CONFIG_ZMK_IDLE_TIMEOUT=10000
# Go to idle state after 2 min (2*60*1000ms)
CONFIG_ZMK_IDLE_TIMEOUT=12000

# Type-C USB on right hand MCU used only for charging and firmware update
CONFIG_ZMK_USB=n

# Increase range
CONFIG_BT_CTLR_PHY_2M=n
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Enable EC11 encoders
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y



